### PR TITLE
Similar to https://github.com/id/zookeeper-el7-rpm/pull/9

### PR DESCRIPTION
**Pull request by jessp01**

### CODE REVIEW

**Comment by id** [comment]
@jessp01 Thanks!
I don't have time right now to test if it works with 2.3 Kafka. Have you tried it?

**Comment by jessp01** [comment]
Hi @id, The build process finished successfully, of course but I haven't tested yet. Will have to get to it soon anyhow, which is why I needed to make these changes and build the package:)
I'll let you know once I have done.

**Comment by jessp01** [comment]
Hi @id,

Got round to testing it. Seems to be working fine.

**Comment by id** [comment]
👍

**Pull request merged**
